'use client'

import { useState, createContext, useContext } from 'react'

export const languages = {
  az: {
    title: 'Am I reachable?',
    subtitle: 'Domain Xarici Əlçatanlıq Skanı',
    scan_date: 'Skan tarixi',
    hosts: 'host',
    open: 'açıq',
    closed: 'bağlı',
    search_placeholder: 'Host, IP, server, texnologiya axtar...',
    all: 'Hamısı',
    f_open: 'Açıq',
    f_closed: 'Bağlı',
    f_nodns: 'DNS yox',
    f_shots: 'Ekran görüntüsü',
    f_cloudflare: 'Cloudflare',
    f_hsts: 'HSTS',
    f_csp: 'CSP',
    f_auth: 'Auth',
    f_error: 'Xəta',
    f_tcp: 'TCP Açıq',
    f_dns_only: 'DNS',
    col_status: 'Status',
    col_host: 'Host',
    col_domain: 'Domain',
    col_ips: 'IP Ünvanlar',
    col_http: 'HTTP',
    col_tcp: 'TCP',
    col_server: 'Server',
    col_tech: 'Texnologiyalar',
    col_sec: 'Təhlükəsizlik',
    col_url: 'URL',
    col_shot: 'Ekran',
    col_time: 'Müddət',
    col_cf: 'Cloudflare',
    zoom: 'Böyüt',
    total_scanned: 'Cəmi taranmış',
    ext_open: 'Xarici əlçatan',
    cl_nodns: 'Bağlı / DNS yox',
    shots_taken: 'Ekran görüntüsü',
    cf_count: 'Cloudflare',
    scan_dur: 'Skan müddəti',
    out_files: 'Çıxış faylları',
    apex: 'apex',
    sub: 'sub',
    start_scan: 'Skanı başlat',
    paste_json: 'JSON-u yapışdırın və ya fayl seçin',
    attach_file: 'JSON fayl əlavə et',
    drag_drop: 'JSON faylı bura sürükleyin',
    workers: 'İşçi sayı',
    timeout: 'Zaman aşımı (ms)',
    screenshot: 'Ekran görüntüsü',
    export: 'İxrac et',
    json_format: 'JSON',
    csv_format: 'CSV',
    html_format: 'HTML',
    new_scan: 'Yeni Skan',
    scan_status: 'Skan gedir...',
    loading: 'Yüklənir...',
    completed: 'Tamamlandı',
    error: 'Xəta',
    details: 'Detallar',
    no_results: 'Filterlərə uyğun nəticə yoxdur',
    http_filter: 'HTTP kodu',
    advanced_filters: 'Ətraflı Filterlər',
    clear_filters: 'Filterləri sıfırla',
    file_selected: 'Fayl seçildi',
    remove_file: 'Faylı sil',
  },
  en: {
    title: 'Am I reachable?',
    subtitle: 'Domain External Reachability Scan',
    scan_date: 'Scan date',
    hosts: 'hosts',
    open: 'open',
    closed: 'closed',
    search_placeholder: 'Search hosts, IPs, servers, technologies...',
    all: 'All',
    f_open: 'Open',
    f_closed: 'Closed',
    f_nodns: 'No DNS',
    f_shots: 'Screenshots',
    f_cloudflare: 'Cloudflare',
    f_hsts: 'HSTS',
    f_csp: 'CSP',
    f_auth: 'Auth',
    f_error: 'Error',
    f_tcp: 'TCP Open',
    f_dns_only: 'DNS Only',
    col_status: 'Status',
    col_host: 'Host',
    col_domain: 'Domain',
    col_ips: 'IP Addresses',
    col_http: 'HTTP',
    col_tcp: 'TCP',
    col_server: 'Server',
    col_tech: 'Technologies',
    col_sec: 'Security',
    col_url: 'URL',
    col_shot: 'Screenshot',
    col_time: 'Time',
    col_cf: 'CF',
    zoom: 'Zoom',
    total_scanned: 'Total scanned',
    ext_open: 'Externally open',
    cl_nodns: 'Closed / No DNS',
    shots_taken: 'Screenshots taken',
    cf_count: 'Cloudflare',
    scan_dur: 'Scan duration',
    out_files: 'Output files',
    apex: 'apex',
    sub: 'sub',
    start_scan: 'Start Scan',
    paste_json: 'Paste JSON or attach a file',
    attach_file: 'Attach JSON File',
    drag_drop: 'Drag & drop a JSON file here',
    workers: 'Workers',
    timeout: 'Timeout (ms)',
    screenshot: 'Screenshots',
    export: 'Export',
    json_format: 'JSON',
    csv_format: 'CSV',
    html_format: 'HTML',
    new_scan: 'New Scan',
    scan_status: 'Scanning...',
    loading: 'Loading...',
    completed: 'Completed',
    error: 'Error',
    details: 'Details',
    no_results: 'No results match your filters',
    http_filter: 'HTTP Code',
    advanced_filters: 'Advanced Filters',
    clear_filters: 'Clear Filters',
    file_selected: 'File selected',
    remove_file: 'Remove file',
  },
  ru: {
    title: 'Am I reachable?',
    subtitle: 'Сканирование внешней доступности доменов',
    scan_date: 'Дата сканирования',
    hosts: 'хостов',
    open: 'открыт.',
    closed: 'закрыт.',
    search_placeholder: 'Поиск по хосту, IP, серверу, технологиям...',
    all: 'Все',
    f_open: 'Открытые',
    f_closed: 'Закрытые',
    f_nodns: 'Нет DNS',
    f_shots: 'Скриншоты',
    f_cloudflare: 'Cloudflare',
    f_hsts: 'HSTS',
    f_csp: 'CSP',
    f_auth: 'Auth',
    f_error: 'Ошибка',
    f_tcp: 'TCP Открыт',
    f_dns_only: 'Только DNS',
    col_status: 'Статус',
    col_host: 'Хост',
    col_domain: 'Домен',
    col_ips: 'IP Адреса',
    col_http: 'HTTP',
    col_tcp: 'TCP',
    col_server: 'Сервер',
    col_tech: 'Технологии',
    col_sec: 'Безопасность',
    col_url: 'URL',
    col_shot: 'Скриншот',
    col_time: 'Время',
    col_cf: 'CF',
    zoom: 'Увеличить',
    total_scanned: 'Всего просканировано',
    ext_open: 'Внешне доступно',
    cl_nodns: 'Закрыто / Нет DNS',
    shots_taken: 'Скриншотов получено',
    cf_count: 'Cloudflare',
    scan_dur: 'Длительность',
    out_files: 'Выходные файлы',
    apex: 'apex',
    sub: 'sub',
    start_scan: 'Начать сканирование',
    paste_json: 'Вставить JSON или выбрать файл',
    attach_file: 'Прикрепить JSON файл',
    drag_drop: 'Перетащите JSON файл сюда',
    workers: 'Рабочих процессов',
    timeout: 'Тайм-аут (мс)',
    screenshot: 'Скриншоты',
    export: 'Экспорт',
    json_format: 'JSON',
    csv_format: 'CSV',
    html_format: 'HTML',
    new_scan: 'Новое сканирование',
    scan_status: 'Сканирование...',
    loading: 'Загрузка...',
    completed: 'Завершено',
    error: 'Ошибка',
    details: 'Детали',
    no_results: 'Нет результатов по вашим фильтрам',
    http_filter: 'HTTP Код',
    advanced_filters: 'Расширенные фильтры',
    clear_filters: 'Сбросить фильтры',
    file_selected: 'Файл выбран',
    remove_file: 'Удалить файл',
  },
} as const

export type Language = keyof typeof languages
export type Translations = typeof languages[Language]

const LanguageContext = createContext<{
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: keyof Translations) => string
} | null>(null)

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    return {
      language: 'en' as Language,
      setLanguage: (_lang: Language) => {},
      t: (key: keyof Translations) => languages.en[key] as string,
    }
  }
  return context
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
  }

  const t = (key: keyof Translations): string => {
    return (languages[language][key] as string) ?? (languages.en[key] as string) ?? key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
