import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export const languages = {
  az: {
    title: 'Am I reachable?',
    subtitle: 'Domain Xarici Əlçatanlıq Skanı',
    scan_date: 'Skan tarixi',
    hosts: 'host',
    open: 'açıq',
    closed: 'bağlı',
    search_placeholder: 'Host, IP, server, texnologiya axtar...',
    all: 'Hamısı',
    f_open: 'Açıq',
    f_closed: 'Bağlı',
    f_nodns: 'DNS yox',
    f_shots: 'Ekran görüntüsü',
    f_cloudflare: 'Cloudflare',
    f_hsts: 'HSTS',
    f_csp: 'CSP',
    f_auth: 'Auth',
    f_error: 'Xəta',
    f_tcp: 'TCP Açıq',
    f_dns_only: 'DNS',
    col_status: 'Status',
    col_host: 'Host',
    col_domain: 'Domain',
    col_ips: 'IP Ünvanlar',
    col_http: 'HTTP',
    col_tcp: 'TCP',
    col_server: 'Server',
    col_tech: 'Texnologiyalar',
    col_sec: 'Təhlükəsizlik',
    col_url: 'URL',
    col_shot: 'Ekran',
    col_time: 'Müddət',
    col_cf: 'Cloudflare',
    zoom: 'Böyüt',
    total_scanned: 'Cəmi taranmış',
    ext_open: 'Xarici əlçatan',
    cl_nodns: 'Bağlı / DNS yox',
    shots_taken: 'Ekran görüntüsü',
    cf_count: 'Cloudflare',
    scan_dur: 'Skan müddəti',
    out_files: 'Çıxış faylları',
    apex: 'apex',
    sub: 'sub',
    start_scan: 'Skanı başlat',
    paste_json: 'JSON-u yapışdırın və ya fayl seçin',
    attach_file: 'JSON fayl əlavə et',
    drag_drop: 'JSON faylı bura sürükleyin',
    workers: 'İşçi sayı',
    timeout: 'Zaman aşımı',
    screenshot: 'Ekran görüntüsü',
    export: 'İxrac et',
    json_format: 'JSON',
    csv_format: 'CSV',
    html_format: 'HTML',
    new_scan: 'Yeni Skan',
    scan_status: 'Skan gedir...',
    loading: 'Yüklənir...',
    completed: 'Tamamlandı',
    error: 'Xəta',
    details: 'Detallar',
    no_results: 'Filterlərə uyğun nəticə yoxdur',
    history: 'Tarixçə',
    no_history: 'Hələ heç bir skan yoxdur',
    clear_history: 'Tarixçəni təmizlə',
    confirm_clear: 'Bütün tarixçəni silmək istəyirsiniz?',
    yes_clear: 'Bəli, sil',
    cancel: 'Ləğv et',
    http_filter: 'HTTP kodu',
    advanced_filters: 'Ətraflı Filterlər',
    clear_filters: 'Filterləri sıfırla',
    file_selected: 'Fayl seçildi',
    remove_file: 'Faylı sil',
  },
  en: {
    title: 'Am I reachable?',
    subtitle: 'Domain External Reachability Scan',
    scan_date: 'Scan date',
    hosts: 'hosts',
    open: 'open',
    closed: 'closed',
    search_placeholder: 'Search hosts, IPs, servers, technologies...',
    all: 'All',
    f_open: 'Open',
    f_closed: 'Closed',
    f_nodns: 'No DNS',
    f_shots: 'Screenshots',
    f_cloudflare: 'Cloudflare',
    f_hsts: 'HSTS',
    f_csp: 'CSP',
    f_auth: 'Auth',
    f_error: 'Error',
    f_tcp: 'TCP Open',
    f_dns_only: 'DNS Only',
    col_status: 'Status',
    col_host: 'Host',
    col_domain: 'Domain',
    col_ips: 'IP Addresses',
    col_http: 'HTTP',
    col_tcp: 'TCP',
    col_server: 'Server',
    col_tech: 'Technologies',
    col_sec: 'Security',
    col_url: 'URL',
    col_shot: 'Screenshot',
    col_time: 'Time',
    col_cf: 'CF',
    zoom: 'Zoom',
    total_scanned: 'Total scanned',
    ext_open: 'Externally open',
    cl_nodns: 'Closed / No DNS',
    shots_taken: 'Screenshots taken',
    cf_count: 'Cloudflare',
    scan_dur: 'Scan duration',
    out_files: 'Output files',
    apex: 'apex',
    sub: 'sub',
    start_scan: 'Start Scan',
    paste_json: 'Paste JSON or attach a file',
    attach_file: 'Attach JSON File',
    drag_drop: 'Drag & drop a JSON file here',
    workers: 'Workers',
    timeout: 'Timeout',
    screenshot: 'Screenshots',
    export: 'Export',
    json_format: 'JSON',
    csv_format: 'CSV',
    html_format: 'HTML',
    new_scan: 'New Scan',
    scan_status: 'Scanning...',
    loading: 'Loading...',
    completed: 'Completed',
    error: 'Error',
    details: 'Details',
    no_results: 'No results match your filters',
    history: 'History',
    no_history: 'No scans yet',
    clear_history: 'Clear history',
    confirm_clear: 'Delete all history?',
    yes_clear: 'Yes, clear',
    cancel: 'Cancel',
    http_filter: 'HTTP Code',
    advanced_filters: 'Advanced Filters',
    clear_filters: 'Clear Filters',
    file_selected: 'File selected',
    remove_file: 'Remove file',
  },
  ru: {
    title: 'Am I reachable?',
    subtitle: 'Сканирование внешней доступности доменов',
    scan_date: 'Дата сканирования',
    hosts: 'хостов',
    open: 'открыт.',
    closed: 'закрыт.',
    search_placeholder: 'Поиск по хосту, IP, серверу, технологиям...',
    all: 'Все',
    f_open: 'Открытые',
    f_closed: 'Закрытые',
    f_nodns: 'Нет DNS',
    f_shots: 'Скриншоты',
    f_cloudflare: 'Cloudflare',
    f_hsts: 'HSTS',
    f_csp: 'CSP',
    f_auth: 'Auth',
    f_error: 'Ошибка',
    f_tcp: 'TCP Открыт',
    f_dns_only: 'Только DNS',
    col_status: 'Статус',
    col_host: 'Хост',
    col_domain: 'Домен',
    col_ips: 'IP Адреса',
    col_http: 'HTTP',
    col_tcp: 'TCP',
    col_server: 'Сервер',
    col_tech: 'Технологии',
    col_sec: 'Безопасность',
    col_url: 'URL',
    col_shot: 'Скриншот',
    col_time: 'Время',
    col_cf: 'CF',
    zoom: 'Увеличить',
    total_scanned: 'Всего просканировано',
    ext_open: 'Внешне доступно',
    cl_nodns: 'Закрыто / Нет DNS',
    shots_taken: 'Скриншотов получено',
    cf_count: 'Cloudflare',
    scan_dur: 'Длительность',
    out_files: 'Выходные файлы',
    apex: 'apex',
    sub: 'sub',
    start_scan: 'Начать сканирование',
    paste_json: 'Вставить JSON или выбрать файл',
    attach_file: 'Прикрепить JSON файл',
    drag_drop: 'Перетащите JSON файл сюда',
    workers: 'Рабочих процессов',
    timeout: 'Тайм-аут',
    screenshot: 'Скриншоты',
    export: 'Экспорт',
    json_format: 'JSON',
    csv_format: 'CSV',
    html_format: 'HTML',
    new_scan: 'Новое сканирование',
    scan_status: 'Сканирование...',
    loading: 'Загрузка...',
    completed: 'Завершено',
    error: 'Ошибка',
    details: 'Детали',
    no_results: 'Нет результатов по вашим фильтрам',
    history: 'История',
    no_history: 'Нет сканирований',
    clear_history: 'Очистить историю',
    confirm_clear: 'Удалить всю историю?',
    yes_clear: 'Да, удалить',
    cancel: 'Отмена',
    http_filter: 'HTTP Код',
    advanced_filters: 'Расширенные фильтры',
    clear_filters: 'Сбросить фильтры',
    file_selected: 'Файл выбран',
    remove_file: 'Удалить файл',
  },
} as const

export type Language = keyof typeof languages
export type TranslationKey = keyof typeof languages['en']

// Zustand store for language — no React Context needed
interface LanguageStore {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: TranslationKey) => string
}

export const useLanguage = create<LanguageStore>()(
  persist(
    (set, get) => ({
      language: 'en' as Language,
      setLanguage: (lang: Language) => set({ language: lang }),
      t: (key: TranslationKey): string => {
        const lang = get().language
        return (languages[lang]?.[key] as string) ?? (languages.en[key] as string) ?? key
      },
    }),
    {
      name: 'air-language',
      partialize: (state) => ({ language: state.language }),
    }
  )
)

// Keep LanguageProvider as a no-op wrapper for backward compat
export function LanguageProvider({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
